# Generated by Django 3.2.5 on 2021-08-19 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Posts', '0004_post_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='website',
        ),
    ]
