# Generated by Django 3.2.5 on 2021-08-19 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Posts', '0006_auto_20210819_1351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-update_to']},
        ),
    ]
